"""Notification utilities for Slack and email alerts."""

from __future__ import annotations

import smtplib
from dataclasses import dataclass
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Literal

import requests
from loguru import logger

from analysis.anomaly_detector import AnomalyReport
from validation.quality_checker import QualityReport

AlertLevel = Literal["urgent", "info"]


@dataclass(slots=True)
class SMTPConfig:
    """SMTP connection settings.

    Attributes:
        host: SMTP server hostname.
        port: SMTP server port.
        user: SMTP username/from address.
        password: SMTP password.
        use_tls: Whether STARTTLS should be used.
    """

    host: str
    port: int
    user: str
    password: str
    use_tls: bool = True


class Notifier:
    """Send pipeline alerts to Slack and email.

    Notification severity rules:
    - urgent: when quality status is FAIL or at least one high-severity anomaly exists.
    - info: when quality status is WARNING/PASS and there are no high-severity anomalies.

    Args:
        quality_report: Quality report generated by validation module.
        anomaly_report: Anomaly report generated by analysis module.
        slack_webhook_url: Slack incoming webhook URL.
        smtp_config: SMTP settings for email alerts.
        timeout_seconds: HTTP timeout for Slack webhook calls.
    """

    def __init__(
        self,
        quality_report: QualityReport,
        anomaly_report: AnomalyReport,
        *,
        slack_webhook_url: str | None = None,
        smtp_config: SMTPConfig | None = None,
        timeout_seconds: float = 8.0,
    ) -> None:
        self.quality_report = quality_report
        self.anomaly_report = anomaly_report
        self.slack_webhook_url = slack_webhook_url
        self.smtp_config = smtp_config
        self.timeout_seconds = timeout_seconds

    def send_slack_alert(self) -> bool:
        """Send an alert to Slack using Incoming Webhook.

        Returns:
            True when message is sent successfully, otherwise False.

        Notes:
            This method never raises to avoid breaking pipeline execution.
        """
        if not self.slack_webhook_url:
            logger.warning("Slack webhook URL not configured. Skipping Slack alert.")
            return False

        try:
            level = self._determine_alert_level()
            payload = self._build_slack_payload(level)
            logger.info("Sending Slack alert with level={}", level)

            response = requests.post(
                self.slack_webhook_url,
                json=payload,
                timeout=self.timeout_seconds,
            )
            response.raise_for_status()
            return True
        except requests.RequestException as exc:
            logger.exception("Slack alert failed: {}", exc)
            return False
        except Exception as exc:  # pragma: no cover
            logger.exception("Unexpected error sending Slack alert: {}", exc)
            return False

    def send_email_alert(self, *, to_email: str) -> bool:
        """Send an HTML email alert using SMTP.

        Args:
            to_email: Recipient email address.

        Returns:
            True when email is sent successfully, otherwise False.

        Notes:
            This method never raises to avoid breaking pipeline execution.
        """
        if not self.smtp_config:
            logger.warning("SMTP configuration not provided. Skipping email alert.")
            return False

        try:
            level = self._determine_alert_level()
            subject = self._build_email_subject(level)
            html_body = self._build_email_html(level)

            message = MIMEMultipart("alternative")
            message["Subject"] = subject
            message["From"] = self.smtp_config.user
            message["To"] = to_email
            message.attach(MIMEText(html_body, "html", "utf-8"))

            logger.info("Sending email alert with level={} to={}", level, to_email)
            with smtplib.SMTP(self.smtp_config.host, self.smtp_config.port) as smtp:
                if self.smtp_config.use_tls:
                    smtp.starttls()
                smtp.login(self.smtp_config.user, self.smtp_config.password)
                smtp.sendmail(
                    self.smtp_config.user,
                    [to_email],
                    message.as_string(),
                )
            return True
        except smtplib.SMTPException as exc:
            logger.exception("Email alert failed: {}", exc)
            return False
        except Exception as exc:  # pragma: no cover
            logger.exception("Unexpected error sending email alert: {}", exc)
            return False

    def _determine_alert_level(self) -> AlertLevel:
        """Determine alert level from quality status and anomaly severities."""
        has_high_anomaly = any(
            finding.severity == "alta" for finding in self.anomaly_report.anomalies
        )
        if self.quality_report.status == "FAIL" or has_high_anomaly:
            return "urgent"
        return "info"

    def _build_slack_payload(self, level: AlertLevel) -> dict:
        """Build Slack blocks payload with markdown."""
        icon = ":rotating_light:" if level == "urgent" else ":information_source:"
        title = "ALERTA URGENTE" if level == "urgent" else "Resumo Informativo"
        anomalies_count = len(self.anomaly_report.anomalies)
        issues_count = len(self.quality_report.issues)

        header_text = f"{icon} *DataSentinel* - {title}"
        details_text = (
            f"*Status de Qualidade:* {self.quality_report.status}\n"
            f"*Score de Qualidade:* {self.quality_report.score:.2f}\n"
            f"*Problemas de Qualidade:* {issues_count}\n"
            f"*Anomalias Detectadas:* {anomalies_count}"
        )

        if level == "urgent":
            guidance = (
                "Acao recomendada: investigar imediatamente os registros afetados "
                "e validar a integridade da fonte."
            )
        else:
            guidance = "Acao recomendada: acompanhar tendencias e revisar na proxima janela."

        return {
            "blocks": [
                {
                    "type": "section",
                    "text": {"type": "mrkdwn", "text": header_text},
                },
                {
                    "type": "section",
                    "text": {"type": "mrkdwn", "text": details_text},
                },
                {
                    "type": "context",
                    "elements": [{"type": "mrkdwn", "text": guidance}],
                },
            ]
        }

    def _build_email_subject(self, level: AlertLevel) -> str:
        """Build email subject based on alert level."""
        if level == "urgent":
            return "[DataSentinel][URGENTE] Alerta de Qualidade/Anomalias"
        return "[DataSentinel][INFO] Resumo de Qualidade e Anomalias"

    def _build_email_html(self, level: AlertLevel) -> str:
        """Build simple HTML body for email notifications."""
        title = "Alerta Urgente" if level == "urgent" else "Resumo Informativo"
        highlight = "#b91c1c" if level == "urgent" else "#1d4ed8"
        anomalies_count = len(self.anomaly_report.anomalies)
        issues_count = len(self.quality_report.issues)

        return f"""<html>
  <body style=\"font-family: Arial, sans-serif;\">
    <h2 style=\"color: {highlight};\">DataSentinel - {title}</h2>
    <p><strong>Status de Qualidade:</strong> {self.quality_report.status}</p>
    <p><strong>Score de Qualidade:</strong> {self.quality_report.score:.2f}</p>
    <p><strong>Problemas de Qualidade:</strong> {issues_count}</p>
    <p><strong>Anomalias Detectadas:</strong> {anomalies_count}</p>
  </body>
</html>
"""
